// Code generated by "stringer -type=opFormat"; DO NOT EDIT.

package processor

import "fmt"

const _opFormat_name = "opFormatRopFormatIopFormatSopFormatBopFormatUopFormatJopFormatNop"

var _opFormat_index = [...]uint8{0, 9, 18, 27, 36, 45, 54, 65}

func (i opFormat) String() string {
	if i >= opFormat(len(_opFormat_index)-1) {
		return fmt.Sprintf("opFormat(%d)", i)
	}
	return _opFormat_name[_opFormat_index[i]:_opFormat_index[i+1]]
}
