// Code generated by "stringer -type=regAddr"; DO NOT EDIT.

package processor

import "fmt"

const _regAddr_name = "zeroraspgptpt0t1t2s0s1a0a1a2a3a4a5a6a7s2s3s4s5s6s7s8s9s10s11t3t4t5t6"

var _regAddr_map = map[regAddr]string{
	1:          _regAddr_name[0:4],
	2:          _regAddr_name[4:6],
	4:          _regAddr_name[6:8],
	8:          _regAddr_name[8:10],
	16:         _regAddr_name[10:12],
	32:         _regAddr_name[12:14],
	64:         _regAddr_name[14:16],
	128:        _regAddr_name[16:18],
	256:        _regAddr_name[18:20],
	512:        _regAddr_name[20:22],
	1024:       _regAddr_name[22:24],
	2048:       _regAddr_name[24:26],
	4096:       _regAddr_name[26:28],
	8192:       _regAddr_name[28:30],
	16384:      _regAddr_name[30:32],
	32768:      _regAddr_name[32:34],
	65536:      _regAddr_name[34:36],
	131072:     _regAddr_name[36:38],
	262144:     _regAddr_name[38:40],
	524288:     _regAddr_name[40:42],
	1048576:    _regAddr_name[42:44],
	2097152:    _regAddr_name[44:46],
	4194304:    _regAddr_name[46:48],
	8388608:    _regAddr_name[48:50],
	16777216:   _regAddr_name[50:52],
	33554432:   _regAddr_name[52:54],
	67108864:   _regAddr_name[54:57],
	134217728:  _regAddr_name[57:60],
	268435456:  _regAddr_name[60:62],
	536870912:  _regAddr_name[62:64],
	1073741824: _regAddr_name[64:66],
	2147483648: _regAddr_name[66:68],
}

func (i regAddr) String() string {
	if str, ok := _regAddr_map[i]; ok {
		return str
	}
	return fmt.Sprintf("regAddr(%d)", i)
}
