// Code generated by "stringer -type=xuOperation"; DO NOT EDIT.

package processor

import "fmt"

const _xuOperation_name = "bypassB"

var _xuOperation_index = [...]uint8{0, 7}

func (i xuOperation) String() string {
	if i >= xuOperation(len(_xuOperation_index)-1) {
		return fmt.Sprintf("xuOperation(%d)", i)
	}
	return _xuOperation_name[_xuOperation_index[i]:_xuOperation_index[i+1]]
}
