// Code generated by "stringer -type=xuSelector"; DO NOT EDIT.

package processor

import "fmt"

const _xuSelector_name = "xuBypassSel"

var _xuSelector_index = [...]uint8{0, 11}

func (i xuSelector) String() string {
	if i >= xuSelector(len(_xuSelector_index)-1) {
		return fmt.Sprintf("xuSelector(%d)", i)
	}
	return _xuSelector_name[_xuSelector_index[i]:_xuSelector_index[i+1]]
}
